/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

/**
 *
 * @author FCOST
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfConfirmarSenha1 = new javax.swing.JPasswordField();
        lbCadastrese = new javax.swing.JLabel();
        lbConfirmeASenha = new javax.swing.JLabel();
        lbCrieUmaSenha = new javax.swing.JLabel();
        lbDigiteSeuNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        pfConfirmarSenha = new javax.swing.JPasswordField();
        btCadastrar = new javax.swing.JButton();
        lbLinkEntrar = new javax.swing.JLabel();
        lbPanel = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receitas com Afeto - Cadastro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCadastrese.setBackground(new java.awt.Color(0, 0, 0));
        lbCadastrese.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbCadastrese.setForeground(new java.awt.Color(254, 136, 1));
        lbCadastrese.setText("Cadastre-se");
        getContentPane().add(lbCadastrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 140, 30));

        lbConfirmeASenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbConfirmeASenha.setText("Confirme a senha");
        getContentPane().add(lbConfirmeASenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 140, -1));

        lbCrieUmaSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCrieUmaSenha.setText("Crie uma senha");
        getContentPane().add(lbCrieUmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 100, -1));

        lbDigiteSeuNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDigiteSeuNome.setText("Digite seu nome");
        getContentPane().add(lbDigiteSeuNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 100, -1));

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 230, 30));
        getContentPane().add(pfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 230, 30));
        getContentPane().add(pfConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 230, 30));

        btCadastrar.setBackground(new java.awt.Color(254, 136, 1));
        btCadastrar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 170, 40));

        lbLinkEntrar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbLinkEntrar.setForeground(new java.awt.Color(254, 136, 1));
        lbLinkEntrar.setText("Já tem uma conta?");
        lbLinkEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLinkEntrarMouseClicked(evt);
            }
        });
        getContentPane().add(lbLinkEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 100, -1));

        lbPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PanelUser.png"))); // NOI18N
        getContentPane().add(lbPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoCadastro .png"))); // NOI18N
        getContentPane().add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Usuario.nomeUsuario = tfNome.getText().trim();
    
      if (Usuario.nomeUsuario.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite um nome antes de continuar!");
        return; 
    }
    String nome = tfNome.getText();
    String senha = new String(pfSenha.getPassword());
    String confirmarSenha = new String(pfConfirmarSenha.getPassword());
    if (nome.isEmpty() || senha.isEmpty() || confirmarSenha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
        
        }
    if (!senha.equals(confirmarSenha)) {
        JOptionPane.showMessageDialog(this, "As senhas não coincidem!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    Usuario.nomeUsuario = nome;
    Usuario.senhaUsuario = senha;
    
    JOptionPane.showMessageDialog(this, "Conta criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    Entrar login = new Entrar();
    login.setVisible(true);
    login.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void lbLinkEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLinkEntrarMouseClicked
        Entrar lgf = new Entrar();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_lbLinkEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JLabel lbCadastrese;
    private javax.swing.JLabel lbConfirmeASenha;
    private javax.swing.JLabel lbCrieUmaSenha;
    private javax.swing.JLabel lbDigiteSeuNome;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbLinkEntrar;
    private javax.swing.JLabel lbPanel;
    private javax.swing.JPasswordField pfConfirmarSenha;
    private javax.swing.JPasswordField pfConfirmarSenha1;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
