/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author FCOST
 */
public class Entrar extends javax.swing.JFrame {

    /**
     * Creates new form Entrar
     */
    public Entrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfSenha = new javax.swing.JPasswordField();
        lbSenha = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbIniciarSecao = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        lbLinkCadastrese = new javax.swing.JLabel();
        lbPanel = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receitas com Afeto - Iniciar Seção");
        setMinimumSize(new java.awt.Dimension(870, 570));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(pfSenha);
        pfSenha.setBounds(550, 270, 230, 30);

        lbSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSenha.setText("Senha");
        getContentPane().add(lbSenha);
        lbSenha.setBounds(550, 250, 100, 16);

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome);
        tfNome.setBounds(550, 210, 230, 30);

        lbNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNome.setText("Nome");
        getContentPane().add(lbNome);
        lbNome.setBounds(550, 190, 100, 16);

        lbIniciarSecao.setBackground(new java.awt.Color(0, 0, 0));
        lbIniciarSecao.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbIniciarSecao.setForeground(new java.awt.Color(254, 136, 1));
        lbIniciarSecao.setText("Iniciar Seção");
        getContentPane().add(lbIniciarSecao);
        lbIniciarSecao.setBounds(590, 130, 150, 30);

        btEntrar.setBackground(new java.awt.Color(254, 136, 1));
        btEntrar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btEntrar.setText("ENTRAR");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar);
        btEntrar.setBounds(580, 340, 170, 40);

        lbLinkCadastrese.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbLinkCadastrese.setForeground(new java.awt.Color(254, 136, 1));
        lbLinkCadastrese.setText("Cadastre-se");
        lbLinkCadastrese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbLinkCadastrese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLinkCadastreseMouseClicked(evt);
            }
        });
        getContentPane().add(lbLinkCadastrese);
        lbLinkCadastrese.setBounds(710, 310, 70, 16);

        lbPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PanelUser.png"))); // NOI18N
        getContentPane().add(lbPanel);
        lbPanel.setBounds(500, 40, 339, 465);

        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoEntrar.png"))); // NOI18N
        lbFundo.setText("jLabel1");
        getContentPane().add(lbFundo);
        lbFundo.setBounds(0, 0, 860, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        String nomeDigitado = tfNome.getText().trim();
    String senhaDigitada = new String(pfSenha.getPassword());
    if (nomeDigitado.isEmpty() || senhaDigitada.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
}
    else if (nomeDigitado.equals(Usuario.nomeUsuario) && senhaDigitada.equals(Usuario.senhaUsuario)) {
        JOptionPane.showMessageDialog(this, "Login realizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        
        Receitas tela = new Receitas();
        tela.setVisible(true);
        this.dispose();  
    } else {
        JOptionPane.showMessageDialog(this, "Nome ou senha incorretos!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    String nome = tfNome.getText(); 
   
    }//GEN-LAST:event_btEntrarActionPerformed

    private void lbLinkCadastreseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLinkCadastreseMouseClicked
        Cadastro rgf = new Cadastro();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbLinkCadastreseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbIniciarSecao;
    private javax.swing.JLabel lbLinkCadastrese;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPanel;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
