/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author FCOST
 */
public class Escrever extends javax.swing.JFrame {

    /**
     * Creates new form Escrever
     */
    public Escrever() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void limparCampos() {     
        tfTitulo.setText("");
        tfIngredientes.setText("");
        tfModoPreparo.setText("");
        tfOrigem.setText("");
        tfTempoPreparo.setText("");
        tfFonte.setText("");
        

    }              
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCima = new javax.swing.JPanel();
        tfLogo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        lbIngredientes = new javax.swing.JLabel();
        tfIngredientes = new javax.swing.JTextField();
        lbModoPreparo = new javax.swing.JLabel();
        tfModoPreparo = new javax.swing.JTextField();
        lbOrigem = new javax.swing.JLabel();
        tfOrigem = new javax.swing.JTextField();
        lbTempoPreparo = new javax.swing.JLabel();
        tfTempoPreparo = new javax.swing.JTextField();
        lbFonte = new javax.swing.JLabel();
        tfFonte = new javax.swing.JTextField();
        lbAdicoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUltimasAdicoes = new javax.swing.JTable();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        Mopcoes = new javax.swing.JMenu();
        JClogin = new javax.swing.JCheckBoxMenuItem();
        JCsair = new javax.swing.JCheckBoxMenuItem();
        jMCadastrar = new javax.swing.JMenu();
        jCMinhasReceitas = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receitas com Afeto - Escrever Receita");

        pnCima.setBackground(new java.awt.Color(230, 94, 41));

        tfLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo.png"))); // NOI18N

        javax.swing.GroupLayout pnCimaLayout = new javax.swing.GroupLayout(pnCima);
        pnCima.setLayout(pnCimaLayout);
        pnCimaLayout.setHorizontalGroup(
            pnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCimaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tfLogo)
                .addContainerGap(744, Short.MAX_VALUE))
        );
        pnCimaLayout.setVerticalGroup(
            pnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCimaLayout.createSequentialGroup()
                .addComponent(tfLogo)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lbTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbTitulo.setText("Título da receita:");

        tfTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfTitulo.setForeground(new java.awt.Color(102, 102, 102));
        tfTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfTituloMouseReleased(evt);
            }
        });

        lbIngredientes.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbIngredientes.setText("Ingredientes:");

        tfIngredientes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfIngredientes.setForeground(new java.awt.Color(102, 102, 102));
        tfIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIngredientesActionPerformed(evt);
            }
        });

        lbModoPreparo.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbModoPreparo.setText("Modo de preparo:");

        tfModoPreparo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfModoPreparo.setForeground(new java.awt.Color(102, 102, 102));

        lbOrigem.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbOrigem.setText("Origem:");

        tfOrigem.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfOrigem.setForeground(new java.awt.Color(102, 102, 102));

        lbTempoPreparo.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbTempoPreparo.setText("Tempo de preparo:");

        tfTempoPreparo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfTempoPreparo.setForeground(new java.awt.Color(102, 102, 102));

        lbFonte.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbFonte.setText("Fonte:");

        tfFonte.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfFonte.setForeground(new java.awt.Color(102, 102, 102));

        lbAdicoes.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbAdicoes.setText("Últimas adições:");

        tbUltimasAdicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prato", "Ingredientes", "Tempo de preparo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbUltimasAdicoes);

        btAdicionar.setBackground(new java.awt.Color(230, 94, 41));
        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AdicionarImg.png"))); // NOI18N
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btEditar.setBackground(new java.awt.Color(44, 44, 44));
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(230, 94, 41));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ApagarImg.png"))); // NOI18N
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(44, 44, 44));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LimparImg.png"))); // NOI18N
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jMenuBar2.setBackground(new java.awt.Color(230, 94, 41));
        jMenuBar2.setForeground(new java.awt.Color(230, 94, 41));

        Mopcoes.setText("Opções");

        JClogin.setSelected(true);
        JClogin.setText("Login");
        JClogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCloginActionPerformed(evt);
            }
        });
        Mopcoes.add(JClogin);

        JCsair.setSelected(true);
        JCsair.setText("Sair");
        JCsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCsairActionPerformed(evt);
            }
        });
        Mopcoes.add(JCsair);

        jMenuBar2.add(Mopcoes);

        jMCadastrar.setText("Receitas");

        jCMinhasReceitas.setSelected(true);
        jCMinhasReceitas.setText("Minhas Receitas");
        jCMinhasReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMinhasReceitasActionPerformed(evt);
            }
        });
        jMCadastrar.add(jCMinhasReceitas);

        jMenuBar2.add(jMCadastrar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbModoPreparo)
                            .addComponent(lbIngredientes)
                            .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfModoPreparo)
                            .addComponent(tfIngredientes)
                            .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAdicoes)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFonte)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfFonte, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lbOrigem)
                                                    .addGap(316, 316, 316))
                                                .addComponent(tfOrigem)
                                                .addComponent(tfTempoPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbTempoPreparo)))))
                            .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIngredientes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbOrigem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTempoPreparo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTempoPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbFonte)
                        .addGap(5, 5, 5)
                        .addComponent(tfFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbModoPreparo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfModoPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAdicoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIngredientesActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
   
    
        String titulo=tfTitulo.getText();
        String ingrediente =tfIngredientes.getText();
        String tempoPreparo=tfTempoPreparo.getText();

        if (titulo.trim().isEmpty()||ingrediente.trim().isEmpty()||tempoPreparo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de adicionar!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tbUltimasAdicoes.getModel();
        model.addRow(new Object[]{titulo, ingrediente, tempoPreparo});

        JOptionPane.showMessageDialog(this, "Receita adicionada com sucesso!");
        limparCampos();

        
    }//GEN-LAST:event_btAdicionarActionPerformed
     private void abrirTelaCadastro() {
    Receitas Escrever = new Receitas(); 
    Escrever.setVisible(true);
    Escrever.setLocationRelativeTo(null);
    this.dispose();
    }
     
      private void abrirLogin() {
        Entrar tela = new Entrar();
        tela.setVisible(true);
        this.dispose();
    }
    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        int selectedRow=tbUltimasAdicoes.getSelectedRow();
        if (selectedRow!=-1) {
            DefaultTableModel model=(DefaultTableModel) tbUltimasAdicoes.getModel();
            tfTitulo.setText(model.getValueAt(selectedRow, 0).toString());
            tfIngredientes.setText(model.getValueAt(selectedRow, 1).toString());
            tfTempoPreparo.setText(model.getValueAt(selectedRow, 2).toString());
            JOptionPane.showMessageDialog(this, "Edite os campos e clique em adicionar para atualizar.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma receita para editar.");
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int selectRow=tbUltimasAdicoes.getSelectedRow();
        if(selectRow!=-1){
            DefaultTableModel model=(DefaultTableModel) tbUltimasAdicoes.getModel();
            model.removeRow(selectRow);
            JOptionPane.showMessageDialog(this, "Receita excluída com sucesso!");

        }else{
            JOptionPane.showMessageDialog(this, "Selecione a receita para excluir");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jCMinhasReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMinhasReceitasActionPerformed
    abrirTelaCadastro();   // TODO add your handling code here:
    }//GEN-LAST:event_jCMinhasReceitasActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
        // TODO add your handlings code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void JCloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCloginActionPerformed
        abrirLogin();
        // TODO add your handling code here:
    }//GEN-LAST:event_JCloginActionPerformed

    private void JCsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCsairActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JCsairActionPerformed

    private void tfTituloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTituloMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTituloMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escrever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escrever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escrever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escrever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escrever().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem JClogin;
    private javax.swing.JCheckBoxMenuItem JCsair;
    private javax.swing.JMenu Mopcoes;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JCheckBoxMenuItem jCMinhasReceitas;
    private javax.swing.JMenu jMCadastrar;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAdicoes;
    private javax.swing.JLabel lbFonte;
    private javax.swing.JLabel lbIngredientes;
    private javax.swing.JLabel lbModoPreparo;
    private javax.swing.JLabel lbOrigem;
    private javax.swing.JLabel lbTempoPreparo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnCima;
    private javax.swing.JTable tbUltimasAdicoes;
    private javax.swing.JTextField tfFonte;
    private javax.swing.JTextField tfIngredientes;
    private javax.swing.JLabel tfLogo;
    private javax.swing.JTextField tfModoPreparo;
    private javax.swing.JTextField tfOrigem;
    private javax.swing.JTextField tfTempoPreparo;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
