/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author FCOST
 */
public class Receitas extends javax.swing.JFrame {

    
    /**
     * Creates new form Receitas
     */
    public Receitas() {
        initComponents();
        iBNomeUsuario.setText(Usuario.nomeUsuario);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private Object ingredientes;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void abrirEscrever() {
    Escrever Escrever = new Escrever(); 
    Escrever.setVisible(true);
    Escrever.setLocationRelativeTo(null);
    this.dispose();
    }
    
    
    
    
    private void pesquisarReceitas() {
    String termoPesquisa = tfPesquisar.getText().trim().toLowerCase(); // Obtém o texto digitado e converte para minúsculas
    DefaultTableModel model = (DefaultTableModel) tbReceitas.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    tbReceitas.setRowSorter(sorter);
   
    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + termoPesquisa, 0));
}
    
    private void excluirReceita() {
    // Obtém o modelo da tabela
    DefaultTableModel model = (DefaultTableModel) tbReceitas.getModel();
    
    // Verifica se alguma linha está selecionada
    int selectedRow = tbReceitas.getSelectedRow();
    
    if (selectedRow != -1) {
        // Remove a linha selecionada
        model.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Receita excluída com sucesso!");
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecione uma receita para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCima = new javax.swing.JPanel();
        tfLogo = new javax.swing.JLabel();
        lbReceitasDe = new javax.swing.JLabel();
        tfPesquisar = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        iBNomeUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReceitas = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        Mopcoes = new javax.swing.JMenu();
        JClogin = new javax.swing.JCheckBoxMenuItem();
        JCsair = new javax.swing.JCheckBoxMenuItem();
        Mreceitas = new javax.swing.JMenu();
        LinkEscrever = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receitas com Afeto - Minhas Receitas");

        pnCima.setBackground(new java.awt.Color(230, 94, 41));

        tfLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo.png"))); // NOI18N

        javax.swing.GroupLayout pnCimaLayout = new javax.swing.GroupLayout(pnCima);
        pnCima.setLayout(pnCimaLayout);
        pnCimaLayout.setHorizontalGroup(
            pnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCimaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tfLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCimaLayout.setVerticalGroup(
            pnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCimaLayout.createSequentialGroup()
                .addComponent(tfLogo)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lbReceitasDe.setBackground(new java.awt.Color(255, 255, 255));
        lbReceitasDe.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lbReceitasDe.setText("Receitas de");

        tfPesquisar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfPesquisar.setForeground(new java.awt.Color(102, 102, 102));
        tfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisarActionPerformed(evt);
            }
        });

        btPesquisar.setBackground(new java.awt.Color(230, 94, 41));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar2Img.png"))); // NOI18N
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(44, 44, 44));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        iBNomeUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        iBNomeUsuario.setForeground(new java.awt.Color(230, 94, 41));

        tbReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prato", "Ingredientes", "Modo de preparo", "Tempo médio", "Origem", "Fonte"
            }
        ));
        tbReceitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReceitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbReceitas);

        jMenuBar2.setBackground(new java.awt.Color(230, 94, 41));
        jMenuBar2.setForeground(new java.awt.Color(230, 94, 41));

        Mopcoes.setText("Opções");

        JClogin.setSelected(true);
        JClogin.setText("Login");
        JClogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCloginActionPerformed(evt);
            }
        });
        Mopcoes.add(JClogin);

        JCsair.setSelected(true);
        JCsair.setText("Sair");
        JCsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCsairActionPerformed(evt);
            }
        });
        Mopcoes.add(JCsair);

        jMenuBar2.add(Mopcoes);

        Mreceitas.setText("Receitas");

        LinkEscrever.setText("Escrever Receitas");
        LinkEscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinkEscreverActionPerformed(evt);
            }
        });
        Mreceitas.add(LinkEscrever);

        jMenuBar2.add(Mreceitas);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tfPesquisar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(440, 440, 440)
                            .addComponent(btExcluir))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbReceitasDe, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(iBNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(260, 260, 260))))
                .addGap(0, 79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbReceitasDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iBNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addComponent(btPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        pesquisarReceitas();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void JCsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCsairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JCsairActionPerformed

    private void LinkEscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinkEscreverActionPerformed
abrirEscrever();
        
    }//GEN-LAST:event_LinkEscreverActionPerformed

    private void JCloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCloginActionPerformed
        Entrar tela = new Entrar();
        tela.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_JCloginActionPerformed

    private void tbReceitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReceitasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbReceitasMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        excluirReceita();
    }//GEN-LAST:event_btExcluirActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem JClogin;
    private javax.swing.JCheckBoxMenuItem JCsair;
    private javax.swing.JMenuItem LinkEscrever;
    private javax.swing.JMenu Mopcoes;
    private javax.swing.JMenu Mreceitas;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel iBNomeUsuario;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbReceitasDe;
    private javax.swing.JPanel pnCima;
    private javax.swing.JTable tbReceitas;
    private javax.swing.JLabel tfLogo;
    private javax.swing.JTextField tfPesquisar;
    // End of variables declaration//GEN-END:variables
}
